using HowlDev.IO.Text.ConfigFile.Enums;
using HowlDev.IO.Text.ConfigFile.Interfaces;
using System.ComponentModel;

namespace HowlDev.IO.Text.ConfigFile.Primitives;

/// <summary/>
[EditorBrowsable(EditorBrowsableState.Never)]
public class ArrayConfigOption : BaseConfigOption {
    private List<IBaseConfigOption> array = [];
    private string resourcePath;

    /// <inheritdoc/>
    public override ConfigOptionType Type => ConfigOptionType.Array;
    /// <inheritdoc/>
    public override int Count => array.Count;
    /// <inheritdoc/>
    public override IEnumerable<IBaseConfigOption> Items => array;

    /// <inheritdoc/>
    public ArrayConfigOption(List<IBaseConfigOption> array, string parentPath = "", string myPath = "") {
        this.array = array;
        resourcePath = parentPath;
        if (myPath.Length > 0) resourcePath += "[" + myPath + "]";
    }

    /// <inheritdoc/>
    public override IBaseConfigOption this[int index] {
        get {
            if (index < 0 || index >= array.Count) {
                string error = $"Index {index} is out of range. This array has {array.Count} items.";
                if (resourcePath.Length >= 3) error += $"\n\tPath: {resourcePath}";
                throw new IndexOutOfRangeException(error);
            }

            return array[index];
        }
    }

    /// <inheritdoc/>
    public override IEnumerable<T> AsEnumerable<T>() => AsEnumerable<T>(new OptionMappingOptions() { UseProperties = true, UseConstructors = true });

    /// <inheritdoc/>
    public override IEnumerable<T> AsEnumerable<T>(OptionMappingOptions options) {
        List<T> values = [];
        // Generated by AI
        foreach (IBaseConfigOption value in array) {
            switch (value.Type) {
                case ConfigOptionType.Primitive:
                    values.Add(value.As<T>());
                    break;
                case ConfigOptionType.Object:
                    values.Add(ObjectConfigOption.Map<T>(options, value.Contains, value));
                    break;
                default:
                    throw new InvalidOperationException($"Cannot map array item of type {value.Type} to {typeof(T).Name}.");
            }
        }

        return values;
    }

    /// <inheritdoc />
    public override IEnumerable<T> AsStrictEnumerable<T>() {
        throw new NotImplementedException();
    }

}