using HowlDev.IO.Text.ConfigFile.Enums;
using HowlDev.IO.Text.ConfigFile.Interfaces;
using System.ComponentModel;

namespace HowlDev.IO.Text.ConfigFile.Primitives;

/// <summary/>
[EditorBrowsable(EditorBrowsableState.Never)]
public class ArrayConfigOption : IBaseConfigOption {
    private List<IBaseConfigOption> array = [];
    private string resourcePath;

    /// <summary/>
    public ConfigOptionType Type => ConfigOptionType.Array;
    /// <summary/>
    public int Count => array.Count;
    /// <summary/>
    public IEnumerable<IBaseConfigOption> Items => array;
    /// <summary/>
    public IEnumerable<string> Keys => throw new InvalidOperationException("Key enumeration not allowed on type of ArrayConfigOption.");

    /// <summary/>
    public ArrayConfigOption(List<IBaseConfigOption> array, string parentPath = "", string myPath = "") {
        this.array = array;
        resourcePath = parentPath;
        if (myPath.Length > 0) resourcePath += "[" + myPath + "]";
    }

    /// <summary/>
    public IBaseConfigOption this[string key] => throw new InvalidOperationException("Operation invalid on type of ArrayConfigOption.");
    /// <summary/>
    public IBaseConfigOption this[int index] {
        get {
            if (index < 0 || index >= array.Count) {
                string error = $"Index {index} is out of range. This array has {array.Count} items.";
                if (resourcePath.Length >= 3) error += $"\n\tPath: {resourcePath}";
                throw new IndexOutOfRangeException(error);
            }

            return array[index];
        }
    }

    /// <inheritdoc/>
    public IEnumerable<T> AsEnumerable<T>() => AsEnumerable<T>(new OptionMappingOptions() { UseProperties = true, UseConstructors = true });

    /// <inheritdoc/>
    public IEnumerable<T> AsEnumerable<T>(OptionMappingOptions options) {
        List<T> values = [];
        // Generated by AI
        foreach (IBaseConfigOption value in array) {
            switch (value.Type) {
                case ConfigOptionType.Primitive:
                    values.Add((T)Convert.ChangeType(value.ToString(null), typeof(T)));
                    break;
                case ConfigOptionType.Object:
                    values.Add(ObjectConfigOption.Map<T>(options, value.Contains, value));
                    break;
                default:
                    throw new InvalidOperationException($"Cannot map array item of type {value.Type} to {typeof(T).Name}.");
            }
        }

        return values;
    }

    /// <summary/>
    public bool TryGet(string key, out IBaseConfigOption value) => throw new InvalidOperationException("TryGet not allowed on type of ArrayConfigOption.");

    /// <summary/>
    public bool Contains(string key) => throw new InvalidOperationException("Contains not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public TypeCode GetTypeCode() => throw new InvalidOperationException("GetTypeCode not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public bool ToBoolean(IFormatProvider? provider) => throw new InvalidOperationException("ToBoolean not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public byte ToByte(IFormatProvider? provider) => throw new InvalidOperationException("ToByte not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public char ToChar(IFormatProvider? provider) => throw new InvalidOperationException("ToChar not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public DateTime ToDateTime(IFormatProvider? provider) => throw new InvalidOperationException("ToDateTime not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public decimal ToDecimal(IFormatProvider? provider) => throw new InvalidOperationException("ToDecimal not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public double ToDouble(IFormatProvider? provider) => throw new InvalidOperationException("ToDouble not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public short ToInt16(IFormatProvider? provider) => throw new InvalidOperationException("ToInt16 not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public int ToInt32(IFormatProvider? provider) => throw new InvalidOperationException("ToInt32 not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public long ToInt64(IFormatProvider? provider) => throw new InvalidOperationException("ToInt64 not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public sbyte ToSByte(IFormatProvider? provider) => throw new InvalidOperationException("ToSByte not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public float ToSingle(IFormatProvider? provider) => throw new InvalidOperationException("ToSingle not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public string ToString(IFormatProvider? provider) => throw new InvalidOperationException("ToString not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public object ToType(Type conversionType, IFormatProvider? provider) => throw new InvalidOperationException("ToType not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public ushort ToUInt16(IFormatProvider? provider) => throw new InvalidOperationException("ToUInt16 not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public uint ToUInt32(IFormatProvider? provider) => throw new InvalidOperationException("ToUInt32 not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public ulong ToUInt64(IFormatProvider? provider) => throw new InvalidOperationException("ToUInt64 not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T As<T>() => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T As<T>(OptionMappingOptions option) => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T AsStrict<T>() => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T AsStrict<T>(OptionMappingOptions option) => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T AsConstructed<T>() => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T AsStrictConstructed<T>() => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T AsProperties<T>() => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");

    /// <inheritdoc/>
    public T AsStrictProperties<T>() => throw new InvalidOperationException("Reflection not allowed on type of ArrayConfigOption.");
}